This is for testing the performance of trained model in model_safer dir

In [1]:
import os
import torch
import torch.nn as nn

from torch.utils.data import DataLoader

from sklearn.metrics import confusion_matrix
import numpy as np

In [2]:
from OCT_loader import oct_loader
from base_resnet import oct_resnet
import datetime

In [3]:
model_path = "../model_safer"
model_name = "base_resnet_adamw.pth"

In [4]:
model_weight = os.path.join(model_path, model_name)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [5]:
model = oct_resnet()
model.load_state_dict(torch.load(model_weight))
model = model.to(device)

In [6]:
val_data = oct_loader(data_type="test")
val_loader = DataLoader(val_data, batch_size=32, shuffle=True)

In [7]:
model.eval()  
all_preds = []  
all_labels = []  


with torch.no_grad():  
    for images, labels in val_loader:
        images, labels = images.to(device), labels.to(device)

        
        output = model(images)
        
        
        _, preds = torch.max(output, 1)
        
        all_preds.extend(preds.cpu().numpy())  
        all_labels.extend(labels.cpu().numpy())  

cm = confusion_matrix(all_labels, all_preds)


print("Confusion Matrix:")
print(cm)


Confusion Matrix:
[[241   1   0   0]
 [  2 238   0   2]
 [ 11   0 231   0]
 [  0   0   0 242]]


In [8]:
count = [cm[n][n] for n in range(4)]
acc_count = sum(count)
acc = acc_count / len(val_data)

In [9]:
acc

0.9834710743801653