This is for testing the performance of trained model in model_safer dir

In [1]:
import os
import torch
import torch.nn as nn

from torch.utils.data import DataLoader

from sklearn.metrics import confusion_matrix
import numpy as np

In [2]:
from OCT_loader import oct_loader
from base_resnet import oct_resnet
from base_vit import oct_vit
from squeeze_vit import SqueezeViT
import datetime

In [18]:
model_path = "../model_safer"
model_name = "svit.pth"

In [19]:
model_weight = os.path.join(model_path, model_name)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [20]:
model = SqueezeViT()
model.load_state_dict(torch.load(model_weight))
model = model.to(device)

C:\Users\13710\AppData\Roaming\Python\Python39\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\13710\AppData\Roaming\Python\Python39\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=SqueezeNet1_1_Weights.IMAGENET1K_V1`. You can also use `weights=SqueezeNet1_1_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [21]:
test_data = oct_loader(data_type="test")
test_loader = DataLoader(test_data, batch_size=32, shuffle=True)

In [22]:
model.eval()  
all_preds = []  
all_labels = []  


with torch.no_grad():  
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)

        
        output = model(images)
        
        
        _, preds = torch.max(output, 1)
        
        all_preds.extend(preds.cpu().numpy())  
        all_labels.extend(labels.cpu().numpy())  

cm = confusion_matrix(all_labels, all_preds)


print("Confusion Matrix:")
print(cm)


Confusion Matrix:
[[242   0   0   0]
 [  1 241   0   0]
 [  2   0 240   0]
 [  0   0   0 242]]


In [16]:
count = [cm[n][n] for n in range(4)]
acc_count = sum(count)
acc = acc_count / len(test_data)

In [ ]:
acc     # SViT

0.996900826446281

In [ ]:
acc       # Resnet

0.9834710743801653

In [17]:
acc        # vit


0.9793388429752066